.golangci.yml
build/Makefile.deps

Bumps golangci meta-linter version to 1.21
Adds a new linter introduced in 1.21 to the ignore list. ( we need to discuss if we want to fix the new errors reported by this linter )

trivial: bump golanci version to 1.21

---

.github/workflows/go.yml

Bumps GitHub Actions to Go 1.13
Go 1.13 is the latest and greatest! And all of the team seems to be running 1.13 anyway.

Bump Go version to 1.13

---

CONTRIBUTING.md

Adds the contributing remark to help contributors have the CI running in their GH actions fork

Add CONTIBUTING note about GitHub Actions in Forks

---

cmd/deployment/shutdown.go
docs/ecctl_deployment.md
docs/ecctl_deployment_shutdown.md
pkg/deployment/shutdown.go
pkg/deployment/shutdown_test.go
pkg/util/helper.go

Adds the deployment shutdown command with an interactive prompt
confirming the action which can be skipped by using the `--force` flag.
```console
$ dev-cli deployment shutdown a3eb4382ccca482ea15ad1232aabf2cc
This action will delete the specified deployment ID and its associated sub-resources, do you want to continue? [y/n]: y
{
"id": "a3eb4382ccca482ea15ad1232aabf2cc",
"name": "",
"orphaned": {
"apm": [],
"appsearch": [],
"elasticsearch": [
{
"dependents": [
{
"id": "7e44eee3e62f416a8512811bd6498d6e",
"kind": "kibana"
}
],
"id": "a3eb4382ccca482ea15ad1232aabf2cc"
}
],
"kibana": []
}
}
```

deployment: Add shutdown command

---

cmd/deployment/command.go
cmd/deployment/delete.go
cmd/deployment/show.go
docs/ecctl_deployment_delete.md
pkg/deployment/delete.go
pkg/deployment/delete_test.go

Adds the deployment delete command which can be used to remove
deployments which have been shut down previously. Additionally renames
`deployment.go` to `command.go`
```console
$ dev-cli deployment delete a3eb4382ccca482ea15ad1232aabf2cc
{
"id": "a3eb4382ccca482ea15ad1232aabf2cc",
"name": "",
"orphaned": {
"apm": [],
"appsearch": [],
"elasticsearch": [
{
"dependents": [
{
"id": "7e44eee3e62f416a8512811bd6498d6e",
"kind": "kibana"
}
],
"id": "a3eb4382ccca482ea15ad1232aabf2cc"
}
],
"kibana": []
}
}
```
```console
$ dev-cli deployment delete 32051ab417b946ee9a3e834e8b29ebaf
{
"errors": [
{
"code": "deployments.deployment_has_instances",
"fields": null,
"message": "Unable to delete deployment [DeploymentId(32051ab417b946ee9a3e834e8b29ebaf)] since it still has instances. …
```

deployment: Add delete command

---

build/errcheck-exclusions.txt
cmd/deployment/create.go
cmd/util/random.go
cmd/util/region.go
docs/ecctl_deployment.md
docs/ecctl_deployment_create.md
docs/ecctl_deployment_delete.md
pkg/deployment/create.go
pkg/deployment/create_test.go
pkg/util/random.go

Adds the deployment create command which enables the creation of
multi-resource deployments from a file definition in one API call. The
main features are two flag overrides (name and version) which allow the
file definition to be used more like a template.
Additionally, a `--request-id` flag is provided which enables setting an
idempotency token for the API calls. By default an auto-generated value
is sent to the API and printed to the Standard Error device so that
users can use the token in case the deployment creation fails.
```
$ dev-cli deployment create -f deployment_example.json --name marcdeploy --version=7.4.1
The deployment creation returned with an error, please use the displayed idempotency token
to recreate the deployment resources
Idempotency token: …
```

deployment: Add create command

---

cmd/deployment/restore.go
docs/ecctl_deployment_restore.md
pkg/deployment/restore.go
pkg/deployment/restore_test.go

Adds the restore command with a --restore-snapshot boolean flag to
trigger snapshot restore on Elasticsearch instances if applicable.

deployment: Add restore command

---

pkg/ecctl/init.go
pkg/ecctl/init_test.go

Hardcodes the configuration for the `init` API calls to skip TLS
validation so that init works out of the box with self-signed TLS
certificates, common in ECE installations.
`ecctl init` doesn't work out of the box with self-signed certificates unless `--insecure` is specified.

init: Skips TLS validation on API calls

---

cmd/init.go

Ensures that the path that holds the configuration file which will be
created already exists.
Resolves elastic/ecctl#46

init: Ensure homepath is created

---

build/Makefile.build
cmd/root.go
cmd/version.go
go.mod
go.sum
main.go
pkg/ecctl/version.go
pkg/ecctl/version_test.go

Extends the `ecctl version` output to include a structured output and a
series of information which was missing:
```console
./bin/ecctl version
Version:               1.0.0-rc1-dev
Client API Version:    2.4.2
Go version:            go1.13.4
Git commit:            8d72808f
Built:                 Fri 15 Nov 09:24:14 2019
OS/Arch:               darwin / amd64
```
Resolves #37
```console
$ make ecctl
$ make version
```

version: Extend output to include ECE API Version

---

docs/ecctl-getting-started.asciidoc
pkg/ecctl/init.go

Removes any mention of the ESS service in the init command and the
default ESS API URL.
Resolves #43

init: Remove mentions of ESS in config bootstrap

---

NOTICE
cmd/root.go
go.mod
go.sum

Adds the defined sdk `api.DefaultTransport` to the default `http.Client`
used by all the API requests. It fixes the issue where responses with a
StatusCode different to those specified in the swagger spec result in
either an `unknown response` or blank response which makes for very bad
UX. After this change, the body of those requests will be shown to the
user.

http: Add api.DefaultTransport in http.Client

---

cmd/deployment/elasticsearch/keystore/command.go
cmd/deployment/elasticsearch/keystore/get.go
cmd/deployment/elasticsearch/keystore/set.go
cmd/deployment/elasticsearch/keystore/show.go
docs/ecctl_deployment_elasticsearch.md
docs/ecctl_deployment_elasticsearch_keystore.md
docs/ecctl_deployment_elasticsearch_keystore_set.md
docs/ecctl_deployment_elasticsearch_keystore_show.md
pkg/deployment/elasticsearch/set_keystore.go
pkg/deployment/elasticsearch/set_keystore_test.go
pkg/deployment/elasticsearch/show_keystore.go
pkg/deployment/elasticsearch/show_keystore_test.go

Adds two new commands, which allow an Elasticsearch cluster's keystore
to be updated and to be shown:
* ecctl deployment elasticsearch keystore set <cluster id> -f def.json
* ecctl deployment elasticsearch keystore show <cluster id>
The specified keystore definition is treated as a partial and the values
in it are used to either create / update the keystore values. Existing
keystore values will not be affected if missing from the request.
Missing elasticsearch keystore management commands.

elasticsearch: Add keystore management commands

---

cmd/deployment/show.go
docs/ecctl_deployment_show.md
pkg/deployment/get.go
pkg/deployment/get_resource.go
pkg/deployment/get_resource_test.go

Fixes the the `deployment show --type=<type>` by removing the harcoded
API calls with the RefId set to `main-<type>`. Additionally solves the
problem of an unspecified (by default) RefId to be autodiscovered with
an API call which obtains the RefId of the resource type when Type is
specified but --ref-id is not.
Additionally adds a `--ref-id` flag which allows the users to override
the default "auto-discovery" behavior and obtain a specific resource if
the RefId is known by the user.
Furthermore, moves all the switch cases to obtain different kind of
resources from the deployment to the more appropriate applicaiton logic
package rather than the `cmd` presentation layer.
Adds an example of this behavior to the help/docs.
Resolves #56.

deployment: Fix show resource type command

---

cmd/init.go

There was a small mistake in the directory permission mask when the
folder `~/.ecctl` does not exist, it was previously creating it without
the execution premission which prevents anyone from actually accessing
the folder.
Additionally it prints the location of the configuration that's been
written down at the end of initialising the config.
Resolves #63
```console
$ make ecctl
[...]
$ rm -rf ~/.ecctl
$ ./bin/ecctl init
Welcome to the Elastic Cloud CLI! This command will guide you through authenticating and setting some default values.
Missing configuration file, would you like to initialise it? [y/n]: y
Enter the URL of your ECE installation: http://somehost:12300
What default output format would you like?
[1] text - Human-readable output format, commands with no output templates defined …
```

cmd: Fix init command on unexisting .ecctl folder

---

cmd/root.go
go.mod
go.sum
pkg/ecctl/init.go

Since the newer release of elastic/cloud-sdk-go@v1.0.0-bc7 already adds
the ErrCatchTransport on the construction of the api client, it is no
longer necessary to handle this on the client's side.
Additionally, changes the order on which the application's insecure flag
is set within `ecctl.InitConfig()`. Since the flag insecure comes with a
set default value (false), setting the value before viper.Unmarshal
causes any of the structure's values to be set to the default value
declared in the cobra flags that have been bound to viper.
Resolves #65 
Manually running `dev-cli init` with an https URL.

Remove ErrCatchTransport from default http client

---

cmd/deployment/plan/cancel.go
cmd/deployment/plan/command.go
docs/ecctl_deployment.md
docs/ecctl_deployment_plan.md
docs/ecctl_deployment_plan_cancel.md
pkg/deployment/depresource/cancel_plan.go
pkg/deployment/depresource/cancel_plan_test.go

Adds the deployment plan cancel command which allows users to cancel
pending plans for specific resources.
The syntax is as follows:
`ecctl deployment plan cancel <deployment id> --type <type> --ref-id <id>`
Implement more of the Deployment resource APIs.
```console
$ ecctl deployment plan cancel fc2fe19a8c4f43d385004febe4e63900 --type kibana --ref-id kibana --force
{
"errors": [
{
"code": "deployments.resource_does_not_have_a_pending_plan",
"fields": null,
"message": "The Resource does not have a pending plan: DeploymentId [fc2fe19a8c4f43d385004febe4e63900], Kind [kibana], ResourceId: [8d37cff942fb482ba7a3cac10eea943a]"
}
]
}
```

cmd: Add deployment plan cancel

---

cmd/deployment/resource/command.go
cmd/deployment/resource/upgrade.go
cmd/deployment/resource/upgrade_help.go
docs/ecctl_deployment.md
docs/ecctl_deployment_resource.md
docs/ecctl_deployment_resource_upgrade.md
pkg/deployment/depresource/upgrade_stateless.go
pkg/deployment/depresource/upgrade_stateless_test.go

Adds a command which allows upgrading a stateless resource as specified
in the help and long description for commands. The supported type is any
of the stateless resource types, which for now are apm, appsearch and
kibana.
Implementing more of the deployment/resource APIs.

cmd: Add deployment resource upgrade command

---

cmd/platform/allocator/vacate.go
docs/ecctl_platform_allocator_vacate.md
pkg/platform/allocator/vacate.go
pkg/platform/allocator/vacate_params.go
pkg/platform/allocator/vacate_test.go

This PR adds support to the `override_failsafe` api parameter as part of the plan overrides
Closes #77 
More successful vacates and more flexibility
Manually by adding UTs and observing that the API call is done with the correct parameters

Support vacate override failsafe

---

cmd/deployment/create.go
cmd/deployment/shutdown.go
cmd/deployment/update.go
docs/ecctl_deployment_create.md
docs/ecctl_deployment_shutdown.md
docs/ecctl_deployment_update.md

Adds the --track flag and resource tracking after a plan change to the
deployment subcommands which incur plan changes: `create`, `update` and
`shutdown`.
Resolves #78 
Manually

cmd: Add --track flag to deployment commands

---

cmd/deployment/resource/shutdown.go
cmd/deployment/resource/shutdown_help.go
docs/ecctl_deployment_resource_shutdown.md
pkg/deployment/depresource/shutdown.go
pkg/deployment/depresource/shutdown_test.go
pkg/deployment/params.go
pkg/deployment/params_test.go
pkg/util/error.go
pkg/util/error_test.go

Adds a `ecctl deployment resource shutdown` command which allows
specific deployment resources to be targetted for shutdown. It requires
two flags: `--ref-id` and `--type` which the user needs to specify as
per the shown help.
Additionally, two optional flags `--hide` and `--skip-snapshot` are
available to toggle those options
Furthermore, it extracts the common fields `API`, `DeploymentID`, `Type`
and `RefID`, adding RefID auto-discovery when not specified.
Manually.

cmd: Add deployment resource shutdown command

---

cmd/deployment/resource/restore.go
docs/ecctl_deployment_resource_restore.md
pkg/deployment/depresource/restore.go
pkg/deployment/depresource/restore_test.go

Adds an `ecctl deployment resource restore` command which restores a
previously shut down individual deployment resource. If ref-id not specified
it's auto-discovered via an API call.
Required flags: `--type`.
Optional flag: `--restore-snapshot` and `--ref-id` 
Manually

cmd: Add deployment resource restore command

---

cmd/deployment/resource/delete.go
docs/ecctl_deployment_resource_delete.md
pkg/deployment/depresource/delete_stateless.go
pkg/deployment/depresource/delete_stateless_test.go

Adds an `ecctl deployment resource delete` command which deletes a
previously shut down deployment resource. If ref-id not specified
it's auto-discovered via an API call.
Required flags: `--type`
Optional flags: `--ref-id`
Manually

cmd: Add deployment resource delete command

---

cmd/deployment/resource/delete.go
pkg/deployment/depresource/delete_stateless.go

Fixes a bug where RefID auto-discovery was broken, and adds extra step to confirm the user wishes to perform a destructive action.
Related: https://github.com/elastic/ecctl/issues/99
Bugfix and destructive actions should ask for confirmation.
Manually

bug: fix resource delete refid discovery and require confirmation

---

cmd/user/key/show.go
pkg/user/auth/admin/getkey.go

Fixes `ecctl user key show` command where the required number of
arguments was invalid and the UserID used in the pkg layer was the key
ID instead of the UserID.
#99

user: Fix key show command

---

Makefile
NOTICE
cmd/version.go
go.mod
go.sum

Removes the check for a newer version against the current ecctl version
since it requires a GitHub Token. It is not the most useful of features
and not well documented. It would be handy to have the ability to check
for newer versions without any request token or authenticaiton. For the
time being I am removing the check.
`ecctl version` doesn't check for updates anymore.

cmd: Remove newer version check on ecctl version

---

cmd/deployment/apm/create.go
cmd/deployment/kibana/create.go

Adds the default region to `ecctl kibana create` and `ecctl apm create`
when creating those from a file definition. If the region is not
specified, the default `ece-region` will be used.
#99 
```console
$ cat deployment_example_esonly.json
{
"name": "my single deployment",
"resources": {
"elasticsearch": [
{
"display_name": "my singlee cluster",
"ref_id": "my-es-cluster",
"plan": {
"deployment_template": {
"id": "default"
},
"elasticsearch": {
"version": "7.5.0"
},
"cluster_topology": [
{
"instance_configuration_id": "data.default",
"memory_per_node": 1024,
"node_count_per_zone": 1,
"node_type": {
"data": true,
"ingest": true,
"master": true,
"ml": false
},
"zone_count": 1
}
]
}
}
]
}
}
$ ecctl deployment create -f deployment_example_esonly.json --track
$ cat …
```

cmd: Add default region to APM and Kibana create

---

cmd/deployment/elasticsearch/diagnose.go
docs/ecctl_deployment_elasticsearch_diagnose.md

Fixes the broken diagnostics command by using `os.Create` rather than
`os.Open` for the .zip bundled file. Additionally adds a notee about a
potentially necessary timeout increase in order to complete the
operation.
#99 
Manually

elasticsearch: Fix broken diagnostics command

---

pkg/platform/stack/stack.go

Skips returning an error on stackpacks which have a __MACOSX packed into
the .zip file.
ECE stack packs seem to have a __MACOSX packed file which is causing the command to return an error.
```console
$ecctl platform stack upload 7.5.1.zip
1 error occurred:
* stackpack.invalid_configuration_version: This version cannot be parsed: [__MACOSX] because: Unknown version string: [__MACOSX]
```
Maually

stack: Skip returning an error on packed __MACOSX

---

cmd/deployment/apm/create.go
cmd/deployment/elasticsearch/upgrade.go
cmd/deployment/kibana/create.go
docs/ecctl_deployment_apm_create.md
docs/ecctl_deployment_elasticsearch_upgrade.md
docs/ecctl_deployment_kibana_create.md

Fixes wording for the `--version` flag, and changes the command description to reflect mandatory arguments.
Related: https://github.com/elastic/ecctl/issues/99
UX

cmd: fix command wording

---

cmd/deployment/elasticsearch/instances/override.go

Signed-off-by: karencfv <karencfv@gmail.com>
Fixes a bug where the usage of a `--force` flag was missing from the `elasticsearch instance override` command
A `--force` flag can be used to avoid the confirm action prompt.
manually and with integration tests!

cmd: Use force flag with instance override

---

cmd/deployment/apm/create.go
cmd/deployment/kibana/create.go
docs/ecctl_deployment_apm_create.md
docs/ecctl_deployment_kibana_create.md
pkg/deployment/depresource/apm.go
pkg/deployment/depresource/apm_test.go
pkg/deployment/depresource/elasticsearch.go
pkg/deployment/depresource/kibana.go
pkg/deployment/depresource/kibana_test.go

Changes the default `refID` values to use a "main-" prefix in order to achieve parity with the UI.
Closes: https://github.com/elastic/cloud-cli/issues/1054
Manually and integration test run

deployments: Change refID defaults to use 'main-' prefix

---

cmd/platform/allocator/vacate.go
docs/ecctl_platform_allocator_vacate.md
pkg/platform/allocator/vacate.go
pkg/platform/allocator/vacate_params.go
pkg/platform/allocator/vacate_test.go

Adds a --skip-tracking flag which will make the whole operation async
and not wait for the deployments to complete moving nodes. Adds an
interactive warning which can be skipped with the `--force` flag.
Resolves #107 
Manually
```console
$ dev-cli platform allocator list
Showing allocators that have instances or are connected in the platform. Use --all flag or --output json to show all
ZONE         ALLOCATOR ID    HOST IP         CAPACITY   FREE      INSTANCES   CONNECTED   MAINTENANCE
ece-zone-0   192.168.44.10   192.168.44.10   14.19GB    14.19GB   0           true        false
ece-zone-2   192.168.44.12   192.168.44.12   14.19GB    12.19GB   2           true        false
ece-zone-1   192.168.44.11   192.168.44.11   14.19GB    12.19GB   2           true        false
$ dev-cli platform …
```

cmd: Add --skip-tracking flag to allocator vacate

---

cmd/deployment/plan/cancel.go
cmd/deployment/resource/delete.go
cmd/deployment/resource/restore.go
cmd/deployment/resource/shutdown.go
cmd/deployment/resource/start-maintenance.go
cmd/deployment/resource/start.go
cmd/deployment/resource/stop-maintenance.go
cmd/deployment/resource/stop.go
cmd/deployment/resource/upgrade.go
cmd/deployment/show.go
cmd/root.go
cmd/util/flag.go
cmd/util/flag_test.go
docs/ecctl_deployment_plan_cancel.md
docs/ecctl_deployment_resource_delete.md
docs/ecctl_deployment_resource_restore.md
docs/ecctl_deployment_resource_shutdown.md
docs/ecctl_deployment_resource_start-maintenance.md
docs/ecctl_deployment_resource_start.md
docs/ecctl_deployment_resource_stop-maintenance.md
docs/ecctl_deployment_resource_stop.md
docs/ecctl_deployment_resource_upgrade.md
docs/ecctl_deployment_show.md
go.mod

Adds autocompletion for all of the `--type` flags specified under
deployment or deployment resource commands. It splits the potential
types into 2 groups, Stateless and Stateful.
It also corrects some of the docs where the flags were marked as
Optional and are actually required.
Resolves #74 
Manually

deployment: Add --type flag autocompletion

---

cmd/deployment/kibana/resync.go
docs/ecctl_deployment_kibana.md
docs/ecctl_deployment_kibana_resync.md
pkg/deployment/kibana/resync.go
pkg/deployment/kibana/resync_test.go

Implements a new  `--all` flag for kibana resync:
```console
$ ecctl deployment kibana resync --all
```
Closes: https://github.com/elastic/cloud-cli/issues/1017
Manual and Unit tests

cmd: add --all flag to kibana resync command

---

cmd/deployment/apm/resync.go
docs/ecctl_deployment_apm.md
docs/ecctl_deployment_apm_resync.md
pkg/deployment/apm/resync.go
pkg/deployment/apm/resync_test.go

Implements a new  `--all` flag for APM resync:
```console
$ ecctl deployment apm resync --all
```
Closes: https://github.com/elastic/cloud-cli/issues/1015
Manual and Unit tests

cmd: add --all flag to apm resync command

---

cmd/deployment/resync.go
docs/ecctl_deployment.md
docs/ecctl_deployment_resync.md
pkg/deployment/resync.go
pkg/deployment/resync_test.go

Implements a new `deployment resync` command which resynchronises a given deployment or all.
```console
$ ecctl deployment resync {<deployment id> | --all}
```
Closes: https://github.com/elastic/cloud-cli/issues/1018
Manual and Unit tests

cmd: Add deployment resync and --all flag

---

cmd/platform/constructor/resync.go
docs/ecctl_platform_constructor_resync.md
pkg/platform/constructor/resync.go
pkg/platform/constructor/resync_test.go

Implements a new `platform constructor resync` command which resynchronises a given constructor or all.
```console
$ ecctl platform constructor resync {<constructor id> | --all}
```
Closes: https://github.com/elastic/cloud-cli/issues/1021
Manual and Unit tests

cmd: add platform constructor resync command and --all flag

---

docs/ecctl-release-notes.asciidoc

This PR updates the release notes in our official documentation with information from Marc's https://github.com/elastic/ecctl/releases/tag/v1.0.0-beta1. 
A couple of notes: 
* There was a workgroup last year that standardized how release notes should be structured for Elastic products. This PR gets us very, very close to that structure, making it the first Cloud product to get there. 
* A "changelog" for other Elastic products means a section that includes only a list of changes, in case you're wondering why the release notes call what is listed under "Detailed changes" in Marc's content the "changelog."
Relates to #123
We had some information in the original release notes and additional information in the changelog Marc created that needed to be combined. 
Built locally to make sure the …

Update the v1.0.0-beta1 release notes with information from Marc's changelog

---

pkg/util/track.go

Changes the default poll period from 1s to 10s, meaning a 10x increase
to a slower polling period. Additionally adjusts the number of accepted
API failues (404 or timeouts) to only 2 exponential backoffs since now
the polling interval is higher which yields the same effect on ensuring
that the pending plan has finished without polling the API so many
times.
This should reduce memory the binary's CPU and network usage as well as
reduced API backpressure.
Part or #121 
Manually

util: Change default tracking poll interval

---

.github/workflows/release.yml
developer_docs/RELEASE.md
scripts/goreleaser
scripts/goreleaser-post-actions.sh
scripts/update-brew-tap.sh

Automates the release process for ecctl binaries in a GitHub action. As
part of automating the release, it has been split into two parts;
running goreleaser and running goreleaser post actions.
Since goreleaser no longer automates the homebrew formula creation or
the upload of binaries to an artifact repository, those actions have
been moved to `scripts/goreleaser-post-actions.sh`, which uploads the
binaries to S3, Creates GitHub release, and updates elastic/homebrew-tap
with the latest ecctl version, binary links and checksums.
Fully automated release process. No more user-tied releases.
Manually

release: Automate release in GitHub action

---

NOTICE
go.mod
go.sum

Updates the `cloud-sdk-go` dependency to ` 1.0.0-beta1`

Update cloud-sdk-go to v1.0.0-beta1

---

go.mod
go.sum

Corrects the cloud-sdk-go version to `v1.0.0-bc10` rather than no `v` prefix.

Point ot the latest cloud-sdk-go version

---

cmd/deployment/apm/create.go
cmd/deployment/create.go
cmd/deployment/kibana/create.go
cmd/deployment/update.go

Fixes the case where an actual region is specified, either in the
config, flag or environment and it is not populated.
Region not being used when specified in deployments.
Manually

deployment: Fix empty region bug when specified

---

.goreleaser.yml
scripts/goreleaser
scripts/goreleaser-post-actions.sh

This change removes the v prefix for all of the artifacts created from
goreleaser and also from the path where the artifacts are then uploaded
to.
Additionally fixes a bug which was calling the release post actions on
goreleaser's snapshot command and an erroneous path since the script is
called by the root Makefile
Resolves #149

release: Remove v prefix from binaries and path

---

.github/workflows/go.yml
.github/workflows/release.yml

Adds the cache action to all workflows so that the Go modules can be
pre-cached
Cached dependencies so builds go faster

build: Add Go module cache for GitHub actions

---

docs/ecctl-getting-started.asciidoc

Removed `$ ecctl auth user key list` command that doesn't work in ESS and updated `ecctl deployment elasticsearch list` command to `ecctl deployment list` to list all active deployments.

Updating ecctl init sample command to run after init

---

go.mod
go.sum

Updates the cloud-sdk-go import to v1.0.0-beta1 which includes a swagger import update.
Closes: https://github.com/elastic/ecctl/issues/165
Unit tests

imports: update sdk to v1.0.0-beta1

---

cmd/platform/runner/show.go
docs/ecctl_platform_runner_show.md
pkg/platform/runner/show.go
pkg/platform/runner/show_test.go
pkg/util/helper.go

Creates an `ecctl runner show <runner-id>` command, which shows information about the specified runner.
Closes: https://github.com/elastic/ecctl/issues/170
Unit tests and by running `go run main.go platform runner show 192.168.44.12` against an ece environment.

cmd: add runner show <runner id> command

---

pkg/platform/allocator/vacate.go
pkg/platform/allocator/vacate_full_test.go
pkg/platform/allocator/vacate_params.go
pkg/platform/allocator/vacate_responses_test.go
pkg/platform/allocator/vacate_test.go

Adds support for AppSearch instances to be moved when the `ecctl
platform allocator vacate` is called, adding support for workload
filtering too.
The only difference with other workloads is that plan tracking is not
supported for AppSearch workloads due to elastic/cloud-sdk-go#34.
Instead, an error message is returned after the vacate operations have
been completed which instructrs the user to check the UI to verify that
the vacate has indeed succeeded, of course this is less than ideal, but
once elastic/cloud-sdk-go#34 is resolved, this will no longer be the
case.
Resolves #175 
```console
$ dev-cli platform allocator vacate 192.168.44.11 --kind appsearch
1 error occurred:
* allocator 192.168.44.11: cluster [716cfd4f68694f5f8c867428c8bf5491][appsearch]: instance is being moved but …
```

allocator: Vacate now moves AppSearch instances

---

pkg/ecctl/init.go
pkg/ecctl/init_test.go

The init command will now ask for the type of infrastructure to determine whether to ask for a custom host address or to use the default ESS public api address (https://api.elastic-cloud.com) .
The output is as follows:
When choosing ESS:
```console
Select which type of infrastructure this configuration will for:
[1] Elastic Cloud (Elasticsearch Service).
[2] Elastic Cloud Enterprise (ECE).
Please enter your choice: 1
What default output format...
```
When choosing ECE:
```console
Select which type of infrastructure this configuration will for:
[1] Elastic Cloud (Elasticsearch Service).
[2] Elastic Cloud Enterprise (ECE).
Please enter your choice: 2
Enter the URL of your ECE installation:
```
Default to https://api.elastic-cloud.com:
```console
Select which type of infrastructure this …
```

cmd: init ask for type of infrastructure and default to ESS config setup

---

cmd/platform/runner/resync.go
docs/ecctl_platform_runner_resync.md
pkg/platform/runner/resync.go
pkg/platform/runner/resync_test.go

This PR introduces a new `ecctl runner resync` command which has the option 
to resync a single runner with the given runner ID, or all runners asynchronously
with an `-all` flag 
Closes: https://github.com/elastic/ecctl/issues/171
n/a
Manually against an ece environment and unit tests.

cmd: new runner resync <runner id>|--all command

---

cmd/deployment/plan/cancel.go
docs/ecctl_deployment_plan_cancel.md

Fixes an issue where a required flag had an "Optional" prefix in the description. I've also taken the opportunity to update the command to use the [recommended CLI syntax](https://developers.google.com/style/code-syntax)
n/a
Our commands shouldn't lie about their flags :)
By running `ecctl deployment plan cancel --help` and `make docs`

cmd: mark --type flag as required for plan cancel

---

cmd/deployment/appsearch/command.go
cmd/deployment/appsearch/create.go
cmd/deployment/appsearch/create_help.go
cmd/deployment/appsearch/show.go
docs/ecctl_deployment_appsearch.md
docs/ecctl_deployment_appsearch_create.md
pkg/deployment/depresource/appsearch.go
pkg/deployment/depresource/appsearch_test.go

Implements a new `ecctl deployment appsearch create --id <deployment id>` command.
Related: https://github.com/elastic/ecctl/issues/166
appsearch needs it's own commands :)
Unit tests and manually by running the following commands against an ECE environment:
- `ecctl deployment appsearch create --id 421b46a30bb84d66b8eeae8802846f3a`
- `ecctl deployment appsearch create --generate-payload --id 421b46a30bb84d66b8eeae8802846f3a --zones 3 --size 4096 > appsearchtest.json`
- `ecctl deployment appsearch create  --id 421b46a30bb84d66b8eeae8802846f3a -f appsearchtest.json `

cmd: new appsearch create --id <deployment id>

---

scripts/Makefile.help

VERSION already has a v and that seemed intentional given usage in
`notes` files.
` make | grep vv || echo okay`

Remove extra v in help file

---

cmd/deployment/appsearch/delete.go
cmd/deployment/appsearch/shutdown.go
docs/ecctl_deployment_appsearch.md
docs/ecctl_deployment_appsearch_delete.md
docs/ecctl_deployment_appsearch_shutdown.md
pkg/deployment/depresource/delete_stateless.go

Implements the new `ecctl deployment appsearch shutdown <deployment id>` and `ecctl deployment appsearch delete <deployment id>` commands
Related https://github.com/elastic/ecctl/issues/166
moar appsearch commands!
unit tests and manually against an ECE environment

cmd: new appsearch shutdown and delete commands

---

pkg/ecctl/init.go
pkg/ecctl/init_test.go

Whenever a user opts to use ESS in the init flow, they will be prompted to select a default region.
```console
Select which type of Elastic Cloud offering you will be working with:
[1] Elasticsearch Service (default).
[2] Elastic Cloud Enterprise (ECE).
[3] Elasticsearch Service Private (ESSP).
Please enter your choice: 1
Using "https://api.elastic-cloud.com" as the API endpoint.
Select a region you would like to have as default:
GCP
[1] us-central1 (Iowa)
[2] us-east4 (N. Virginia)
[3] us-west1 (Oregon)
[4] northamerica-northeast1 (Montreal)
[5] australia-southeast1 (Sydney)
[6] europe-west1 (Belgium)
[7] europe-west2 (London)
[8] europe-west3 (Frankfurt)
[9] asia-northeast1 (Tokyo)
[10] asia-south1 (Mumbai)
AWS
[11] us-east-1 (N. Virginia)
[12] us-west-1 (N. California)
[13] us-west-2 …
```

cmd: init gives you a choice to select default region when ESS is selected

---

pkg/ecctl/init.go
pkg/ecctl/init_test.go

The `ecctl init` command disables the option to configure user/pass authentication for ESS and ESSP.
ECE auth configuration stays the same.
Closes: https://github.com/elastic/ecctl/issues/157
Manually and through unit tests

cmd: init now only allows API key auth for ESS users

---

cmd/deployment/appsearch/upgrade.go
docs/ecctl_deployment_appsearch.md
docs/ecctl_deployment_appsearch_upgrade.md

Implements an `ecctl appsearch upgrade <deployment id>` command which upgrades the AppSearch deployment to match the Elasticsearch deployment.
Related: https://github.com/elastic/ecctl/issues/166
all the appsearch commands!
Manually and unit tests

cmd: new appsearch upgrade <deployment id>

---

cmd/platform/runner/search.go
cmd/util/flag.go
cmd/util/flag_test.go
docs/ecctl_platform_runner_search.md
pkg/platform/runner/search.go
pkg/platform/runner/search_test.go

Implements a new `ecctl runner search` command with two optional --query and --file flags.
Also a tiny refactor to the allocator search command to include two new flag helper functions.
Related: https://github.com/elastic/ecctl/issues/154
moar runner commands!
Manually and unit tests

cmd: new runner search

---

README.md
docs/ecctl-getting-started.asciidoc

Documentation change to specify that ecctl is no longer ECE specific.
The docs have also been slightly modified to cater to our largest user base which will be ESS.
Closes: https://github.com/elastic/ecctl/issues/161
ESS public API launch!
n/a

docs: change to specify that ecctl is no longer ECE specific

---

pkg/ecctl/init.go
pkg/ecctl/init_test.go

Changes the message returned when the API call to validate the API key
cannot be made, and tries a different api (GET /deployments) before
returning a more curated error.
#161 
Provide better messages for the init workflow.
Manually
### Incorrect credentials
```console
$ ecctl init
Welcome to Elastic Cloud Control (ecctl)! This command will guide you through authenticating and setting some default values.
Missing configuration file, would you like to initialise it? [y/n]: y
Select which type of Elastic Cloud offering you will be working with:
[1] Elasticsearch Service (default).
[2] Elastic Cloud Enterprise (ECE).
[3] Elasticsearch Service Private (ESSP).
Please enter your choice: 2
Enter the URL of your ECE installation: https://PUBLIC_API
Which authentication mechanism would you like to …
```

init: Provide alternative API validation call

---

cmd/deployment/show.go
docs/ecctl_deployment_show.md
pkg/deployment/deputil/deputil.go
pkg/deployment/get.go

Adds a `--plan-history` flag to `ecctl deployment show` to be able to
obtain the Deployment's plan history.
While working on elastic/cloud-sdk-go#34 I noticed that there
was no way to obtain the plan history through ecctl. So added this flag.
Manually.

deployment: Add --plan-history flag to show cmd

---

.github/workflows/release.yml

Changes the GitHub Personal Access Token which is used to create a PR
against elastic/tap to update ecctl's homebrew formula.
Resolves #140

release: Change GitHub token for Tap modifications

---

pkg/deployment/depresource/apm.go
pkg/deployment/depresource/apm_test.go
pkg/deployment/depresource/appsearch.go
pkg/deployment/depresource/appsearch_test.go

Fixes a bug where the application would panic if it could not find the desired resource kind in the deployment template.
Found while working on https://github.com/elastic/ecctl/issues/116
panics are annoying
Manually and through unit tests

cmd: Handle case when deployment template does not include resource

---

pkg/deployment/depresource/kibana.go
pkg/deployment/depresource/kibana_test.go

Fixes a bug where the application would panic if it could not find the desired resource kind in the deployment template.
https://github.com/elastic/ecctl/pull/205
Manually and unit tests

cmd: Handle case when deployment template does not include kibana

---

cmd/init.go
pkg/ecctl/init.go
pkg/ecctl/init_test.go

Reverts back to printing ECE only information through a boolean
parameter in the Params struct which controls which workflow is used.
Public API is still not available. Will disable this toggle once it is.
Manually
```console
$ ecctl init
Welcome to Elastic Cloud Control (ecctl)! This command will guide you through authenticating and setting some default values.
Missing configuration file, would you like to initialise it? [y/n]: y
Enter the URL of your ECE installation: https://XXXX:12343
Which authentication mechanism would you like to use?
[1] API Keys (Recommended).
[2] Username and Password login.
Please enter your choice: 2
Type in your username: admin
Type in your password:
What default output format would you like?
[1] text - Human-readable output format, commands with no output …
```

init: Revert to ECE only workflow with bool toggle

---

pkg/ecctl/init.go

Changes the example command after a successful ecctl initialization from
`ecctl deployment elasticsearch list` to `ecctl deployment list`.
Resolves #216

init: Change example command to deployment list

---

cmd/platform/deployment-template/command.go
docs/ecctl_platform.md
docs/ecctl_platform_deployment-template.md
docs/ecctl_platform_deployment-template_create.md
docs/ecctl_platform_deployment-template_delete.md
docs/ecctl_platform_deployment-template_list.md
docs/ecctl_platform_deployment-template_pull.md
docs/ecctl_platform_deployment-template_show.md
docs/ecctl_platform_deployment-template_update.md

Adds text to specify that deployment template commands are ECE specific.
Closes: https://github.com/elastic/ecctl/issues/229
By running `make docs`

cmd: specify that deployment template commands are ECE specific

---

cmd/deployment/delete.go
docs/ecctl_deployment.md
docs/ecctl_deployment_delete.md

Adds text to specify that the deployment delete command is ECE specific.
Closes: https://github.com/elastic/ecctl/issues/231
By running `make docs`

cmd: specify that deployment delete command is ECE specific

---

cmd/deployment/create.go
cmd/deployment/create_help.go
docs/ecctl_deployment_create.md

This change temporarily removes the ability to create a flag based deployment until reads to deployment templates are available to all users.
Currently only ECE users have permissions to perform reads on deployment templates. To create a flag based deployment all users would need these permissions. We will wait until these endpoints are available to all to reinstate flag based deployment creation.
Manually by running the command and by running `make docs`

cmd: Temporarily remove ability to create a flag based deployment

---

go.mod
go.sum

Reverts the multierror dependency to 1.0.0 as it requires Go1.14 and can cause problems since we are still on Go1.13.
Also ran go mod tidy

deps: revert multierror to 1.0.0

---

cmd/util/track_params_test.go

Adds the uncommited file which has tests for `NewTrackParams`.
#234

cmd: Add missing NewTrackParams tests

---

.github/CODEOWNERS

Adds delivery team as codeowners for the `docs/` directory

misc: Add delivery team as docs codeowner

---

cmd/platform/allocator/vacate.go
cmd/platform/allocator/vacate_test.go
docs/ecctl_platform_allocator.adoc
docs/ecctl_platform_allocator.md
docs/ecctl_platform_allocator_vacate.adoc
docs/ecctl_platform_allocator_vacate.md

This PR changes the `--cluster` flag to `--resource-id`  for allocator vacate and improves wording within the command
As we move away from the clusters api, the correct term is "resource" instead of "cluster"
Unit tests

cmd: Change --cluster flag to --resource-id 

---

cmd/init.go
pkg/ecctl/init.go
pkg/ecctl/init_test.go

Reverts a feature flag which hid ESS options when using the `ecctl init` command.
This change also adds 3 more regions to the init command.
Related: #161 
Manually and through unit tests

cmd: Show ESS options in init command flow

---

cmd/deployment/shutdown.go
docs/ecctl_deployment_shutdown.adoc
docs/ecctl_deployment_shutdown.md
pkg/deployment/shutdown.go

This patch removes the `--hide` flag from the `ecctl deployment shutdown` command.
There was an issue where even if set to false, the API would return the following error if your user role was anything but "platform administrator": `"Parameter [hide] is restricted and can only be set by a Platform administrator"`.
As the shut down deployments are now hidden by default anyway, there is no need for the `--hide` flag anymore.
```console
$ go run main.go --config ess deployment shutdown 6abe0439ac766e4903faa1dbcb38e904
This action will delete the specified deployment ID and its associated sub-resources, do you want to continue? [y/n]: y
{
"id": "6abe0439ac766e4903faa1dbcb38e904",
"name": "6abe0439ac766e4903faa1dbcb38e904",
<...>
}
$ go run main.go --config ess deployment list --output json
{ …
```

cmd: fix deployment shutdown command

---

README.md

Just a minor change to the main readme.md file, in preparation for public API release.

omitting ece-only support statement from readme

---

docs/ecctl-getting-started.asciidoc

This adds usage examples into the Cloud ecctl guide, basically matching the CRUD examples we have for the public API.  
(This is a duplicate of #277 but I hadn't signed my commits there and creating a new PR seems easier than fixing that.)

Docs: add usages examples to ecctl docs

---

cmd/deployment/create_help.go
docs/ecctl_deployment_create.adoc
docs/ecctl_deployment_create.md

**DO NOT MERGE until current release cycle has finalised and the following link works: https://elastic.co/guide/en/cloud/current/ec-api-deployment-crud.html#ec_create_a_deployment**
In preparations to the upcoming release, this PR updates the output of the `ecctl deployment create --help` command to include a link to our official documentation.
Related: https://github.com/elastic/ecctl/issues/161
By running `make docs`

docs: Update deployment create help wording

---

.github/workflows/release.yml
notes/v1.0.0-beta3.md
scripts/changelog.tpl.md
scripts/goreleaser-post-actions.sh
scripts/update-brew-tap.sh

Fixes the Changelog notes to have the version in the first line as it's
the title that GitHub will use for the release.
Additionally, fixes the issue where the git config doesn't have any user
set, now the script configures it when the settings are missing.
Last, corrects the `GITHUB_USER` to `elasticcloudmachine` when
updating the home-brew tap.
Failing release action.

release: Fix git config and changelog format

---

docs/ecctl_deployment_apm_create.adoc
docs/ecctl_deployment_kibana_create.adoc

We're doing some reorganization of the ECE book, so this fixes two links that will break as a result of that change. I believe we'll have to merge this at the same time as the ECE changes to avoid a docs build break.

Docs: Fix links to ECE API definitions (1.0.0-beta2)

---

docs/ecctl-getting-started.asciidoc

Adds a `--track` flag to the deployment examples, additionally, fixes
the syntax highlighting from `json` to `sh` in a couple of cases.

docs: Add --track flag to the deployment examples

---

cmd/platform/allocator/list.go
cmd/platform/allocator/maintenance.go
cmd/platform/allocator/metadata/command.go
cmd/platform/allocator/search.go
cmd/platform/allocator/show.go
cmd/platform/allocator/vacate.go
cmd/root.go
go.mod
go.sum

Populates the new `Region` parameter on all of the allocatorapi calls
and their parameters, and defaults the region to `ece-region` when the
target host is not the ESS endpoint.
Requires https://github.com/elastic/cloud-sdk-go/pull/133 to be merged.
Manually

allocator: Populate allocatorapi Region parameter

---

NOTICE
cmd/platform/allocator/vacate.go
go.mod
go.sum

Removes the last unprefixed multierror and tidies the `go.sum` and re-
generates the NOTICE file.
Resolves #281

allocator: Remove the last hashicorp/go-multierror

---

cmd/platform/enrollment-token/create.go
cmd/platform/enrollment-token/delete.go
cmd/platform/enrollment-token/list.go

Updates the enrollment-token commands to use the region per API call.
Requires elastic/cloud-sdk-go#137 to be merged.

enrollment-token: Populate Region field API calls

---

cmd/platform/deployment-template/command.go
cmd/platform/deployment-template/create.go
cmd/platform/deployment-template/delete.go
cmd/platform/deployment-template/list.go
cmd/platform/deployment-template/pull.go
cmd/platform/deployment-template/show.go
cmd/platform/deployment-template/update.go
go.mod
go.sum

Updates the `deployment-template` commands to use a `region` on the API
calls to the SDK.
Requires elastic/cloud-sdk-go#146 to be merged.

deployment-template: Update commands with region

---

cmd/deployment/create.go
cmd/root.go

Removes the default "ece-region" assignment on the deployment create cmd
layer when the region is empty and the endpoint is not targetting ESS.
It only affects a flag-based creation and not the payload.
The assignment is already taken care of here: https://github.com/elastic/ecctl/blob/master/cmd/root.go#L187-L189

deployment create: Remove region value on non-ESS

---

cmd/deployment/create.go
cmd/deployment/create_test.go
cmd/deployment/testdata/create-aws.json
cmd/deployment/testdata/create-azure.json
cmd/util/testutils/cmd.go
cmd/util/testutils/testutils.go
cmd/util/testutils/testutils_test.go
cmd/util/track_params.go
go.mod

Adds a new function to the `testutils` package which allow easier
testing to be written on the `cmd` layer.
All the heavy lifting is done by `testutils.RunCmdAssertion` on the test
function, namely it:
1. Initializes the `ecctl.App` singleton from a `testutils.MockCfg`.
2. Sets the cobra `cmd.Command` Err and Out to `*Bytes.Buffer`s.
3. Executes the command with the specified Args.
4. Asserts the returned errors by `cmd.Execute()`
5. Asserts the written data to both the `Err` and `Out` buffers.
6. `ecctl.Cleanup` is called before returning so no instance is set.
It is important to note that global flags won't be parsed and instead,
must be provided as values to `testutils.MockCfg`. As new global flags
are added, the structure should be maintained to contain these.
Interaction with the …

cmd/util/testutils: Add RunCmdAssertion test function

---

cmd/platform/instance-configuration/create.go
cmd/platform/instance-configuration/delete.go
cmd/platform/instance-configuration/list.go
cmd/platform/instance-configuration/pull.go
cmd/platform/instance-configuration/show.go
cmd/platform/instance-configuration/update.go

Splits `command.go` into individual command files, populating the Region
property on each of the commands.
Depends on the open PRs to update `go.mod`

instance-configuration: Add region to commands

---

cmd/deployment/create.go
cmd/platform/deployment-template/create.go
cmd/platform/deployment-template/update.go
cmd/platform/instance-configuration/create.go
cmd/platform/instance-configuration/update.go
cmd/platform/repository/create.go

Using the `sdkcmdutil.FileOrStdin` does not work well when coupled with
Ansible since it thinks the Stdin is always populated even when not.
Resolves #318
Make most `ecctl` commands which have a `--file` flag work with Ansible.
Using `ansible-playbook`

cmd: Remove sdkcmdutil.FileOrStdin use

---

go.mod
go.sum

Updates two modules (`github.com/spf13/cobra` and `golang.org/x/crypto`)
to the latest available versions.
Additionally, bumps the required Go version to `1.13` since it requires
it anyway to make use of `http.Transport.Clone()` and anything prior to
`1.13` won't work.
#335

mod: Update cobra, crypto and Go required verisons

---

cmd/platform/allocator/vacate.go
docs/ecctl_platform_allocator_vacate.adoc
docs/ecctl_platform_allocator_vacate.md
scripts/generate-docs.sh

Adds all the available vacate kinds to the allocator vacate `--kind`
flag and modifies the doc generation command to use volumes (compatible)
with docker remote engines.
#335 
`make docs`

docs: Add all vacate kinds to `--kind` flag

---

cmd/root.go
cmd/root_test.go
pkg/ecctl/app.go

Instead of relying on the `cloud-sdk-go/<version>` default, use ecctl's
current version with an `ecctl/` prefix.
Resolves #333 
Added some unit tests and also tested manually:
```console
$ ./bin/ecctl --config=ess deployment list --verbose
Using config file: /Users/marc/.ecctl/ess.yml
==================== Start of Request #0 ====================
GET /api/v1/deployments HTTP/1.1
Host: api.elastic-cloud.com
User-Agent: ecctl/v1.0.0-beta3-dev
Accept: application/json
Authorization: ApiKey [REDACTED]
Accept-Encoding: gzip
====================  End of Request #0  ====================
```

useragent: Add ecctl/<version> UserAgent header

---

cmd/deployment/create.go
cmd/deployment/create_help.go
cmd/deployment/create_test.go
docs/ecctl_deployment_create.adoc
docs/ecctl_deployment_create.md
go.mod
go.sum

**Requires https://github.com/elastic/cloud-sdk-go/pull/168 to be merged**
Re-enables `ecctl deployment create` flags (https://github.com/elastic/ecctl/pull/239)
Also, there is now support for Enterprise Search and the default deployment 
template is chosen based on cloud provider.
Closes https://github.com/elastic/ecctl/issues/334
tests and manually running the command many times

deployment: create flags reenabled and Enterprise Search support

---

cmd/platform/allocator/vacate.go
docs/ecctl_platform_allocator_vacate.adoc
docs/ecctl_platform_allocator_vacate.md

Fixes a bug where the `--target` parameter was being ignored due to the
flag parsing using `GetStringSlice` when the flag decaration is `Array`.
The bug changes the type from an ArrayString to SliceString.
Additionally, fixes `--maintenance` call which is missing a region value.
`--target` flag was being incorrectly parsed.
Manually.

allocator: Fix Array parsing to slice parsing

---

cmd/deployment/create.go
cmd/deployment/create_test.go
go.mod
go.sum

Fixes the `deployment create` command to be able to pull the deployment
templates by listing them using the API.
Additionally fixes the missing version on statless resources when the
version flag is not specified and it's a flag-based create.
Last, fixes the create tests which weren't testing the create workflow
on the flag-based scenario.
Requires elastic/cloud-sdk-go#178 to be merged.
Part of #335

deployment: Fix create command against ESS

---

cmd/deployment/create.go
cmd/deployment/create_help.go
cmd/deployment/create_test.go
cmd/deployment/show.go
cmd/deployment/show_test.go
cmd/deployment/testdata/show-resource.json
cmd/deployment/testdata/show.json
docs/ecctl_deployment_create.adoc
docs/ecctl_deployment_create.md

The Enterprise Search resource kind is used everywhere as `enterprise_search`.
In order to have feature parity with the API, the deployment create flags have changed 
to use this format as well.
Additionally, a small bug has been fixed where the `deployment list` command did not support
Enterprise Search. Instead of adding `enterprise_search` to the list of resource kinds,
It's preferable to remove that check altogether and let the API return the validation error
like the other commands that use a `--kind` flag
https://github.com/elastic/ecctl/issues/335
feature parity
unit tests and by manually running the commands

create: Use standard enterprise_search instead of enterprise-search

---

cmd/deployment/create.go
cmd/deployment/create_help.go
cmd/deployment/create_test.go
docs/ecctl_deployment_create.adoc
docs/ecctl_deployment_create.md
go.mod
go.sum

The `Name` field in the elasticsearch topology element has changed to `NodeType`
This patch updates the documentation to take that change into account, as well as
changing the `--topology-element` flag to `--es-node-topology` as an UX improvement.
https://github.com/elastic/cloud-sdk-go/pull/182
https://github.com/elastic/ecctl/issues/335
UX
by running the command and unit test

deployment: Change of terminology for create command

---

cmd/deployment/create.go
cmd/deployment/create_help.go
cmd/deployment/create_test.go
docs/ecctl_deployment_create.adoc
docs/ecctl_deployment_create.md

In order to improve UX, all size flags take memory size in gigabytes instead
of megabytes.
Rather than making large modifications in the SDK, a helper function has 
been added to the command layer.
https://github.com/elastic/ecctl/issues/335
UX
manually and unit tests

deployment: Support memory in GB for create command

---

cmd/platform/allocator/metadata/command.go

Fixes an issue where the `ecctl platform allocator metadata {delete | show}`
commands where not setting the `Region` field.

cmd: Add region parameter to allocator metadata

---

cmd/deployment/note/command.go

Fixes an issue where the `ecctl deployment note` commands did not have the
`Region` parameter set.
Additionally, a small bug has been fixed where the ID that is meant to be passed to
the API is the Elasticsearch ID, not the deployment ID.
Manually running all the commands against an ECE environment.

cmd: Fix deployment note commands

---

scripts/changelog.tpl.md
scripts/generate-changelog.sh

Fixes  the interpolated version for the release document in the GitHub
release to equal to `$MAJOR.MINOR` rather than the whole version string.
Additionally, makes the git tag listing match full versions ignoring BCs,
Betas and tags with no `v` prefix.
Broken release notes link.
By running `make changelog`

release: Fix changelog generator broken link

---

scripts/generate-docs.sh

Adds an asciidoc document validator in the `make docs` target.
Resolves #289

docs: Add asciidoc document validator in make docs

---

cmd/platform/allocator/list.go
docs/ecctl_platform_allocator_list.adoc
docs/ecctl_platform_allocator_list.md

Fixes the wording on the `platform allocator list --all` flag to be more
accurate with what's happening behind the scenes.
Expectation that using the `--all` flag would return all the allocators in a region, but it's not the
flag's effect.

allocator: Amend --all flag description

---

.github/workflows/go.yml
.github/workflows/release.yml

We've been on go `1.13` for a while and go 1.15 is out and has many
advantages over go `1.15`. This patch updates to the new version.

go: Update to go 1.15

---

cmd/root.go
cmd/root_test.go

Fixes the problem where the `EC_API_KEY` environment variable wasn't
read.
The problem was that `viper` (correctly) unpacked the `EC_API_KEY` as
`api-key`, and since the `mapstructure` tags (in ecctl.Config) reference
`api_key`, the key is correctly un-marshaled when a config file is read,
but not when set via environment variables.
The fix is to set an alias `api_key` to the existing `api-key` key,
which is done in `cmd/root.go:143`.
v.RegisterAlias("api_key", "api-key")
The rest of the patch is necessary to provide at least some unit tests
to be able to assert this behavior.
Part of #376 
unit tested and tried against production ESS.

fix: ignored EC_API_KEY environment variable

---

cmd/platform/proxy/filteredgroup/update.go
docs/ecctl_platform_proxy_filtered-group_update.adoc
docs/ecctl_platform_proxy_filtered-group_update.md
go.mod
go.sum

Bumps the sdk version to latest commit to get the latest sdk clients
Side-effect : the ProxyFilteredGroupUpdate command option `version` is now a string (was int64`)
Closes https://github.com/elastic/ecctl/issues/391
Make ecctl great again
I confirmed the role list command works fine now

mod: bump sdk version to fc4e5b0 commit hash

---

scripts/update-brew-tap.sh

Adds a `git config --global hub.protocol https` to the `update-brew-tap`
script which was failing with:
fatal: could not read Username for 'https://github.com': No such
device or address
#382

release: (1.0) Add hub.protocol https to script

---

scripts/update-brew-tap.sh

Adds a `git config --global hub.protocol https` to the `update-brew-tap`
script which was failing with:
fatal: could not read Username for 'https://github.com': No such
device or address
#382

release: Add hub.protocol https to script

---

go.mod
go.sum

Updates the `elastic/cloud-sdk-go` module to the latest commit `6fc0976`
which fixes a formatting bug for JSON formatted vacate errors.

mod: Update cloud-sdk-go to 6fc0976

---

go.mod
go.sum

Updates SDK dependency to the latest commit (fa5926f) to include
a fix for the `ecctl deployment show <ID> --generate update-payload`
command, where there would be a panic if a `size` object was empty.
Additionally, this also includes a fix where the `ecctl stack list` command
was not ordering versions correctly.
Closes: https://github.com/elastic/ecctl/issues/413

deps: Update SDK to fix --generate-update-payload and stack list

---

go.mod
go.sum

Fixes bug where `deployment show <id> --generate-update-payload` panics
when the deployment is using legacy `memory_per_node` instead of the
`size.value` notation for sizing.
Closes #421

mod: Update sdk to fix deployment show bug

---

.github/workflows/release.yml

Adds a new `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment var to 
fix the release GH action which was unable to install hub.
https://github.com/elastic/ecctl/actions/runs/557220539
I don't want to release `1.2.0` manually.
I can't test this manually, the release job will have to be run again

build: Fix release GH action

---

docs/release_notes/v1.2.0.adoc

https://github.com/elastic/ecctl/issues/436 does not build because of : 
```
WARNING: invalid reference: ecctl-release-notes-v1.2.0-whats-new
```
According to https://github.com/elastic/docs/pull/2059#issuecomment-779927833 this is the way to fix it

Fix 1.2.0 release notes not building for docs/pull/2059

---

docs/release_notes/v1.2.0.adoc

backport of https://github.com/elastic/ecctl/pull/444

[backport] Fix 1.2.0 release notes not building for docs/pull/2059

---

cmd/deployment/note/command.go
docs/ecctl_deployment.adoc
docs/ecctl_deployment.md
docs/ecctl_deployment_note.adoc
docs/ecctl_deployment_note.md
docs/ecctl_deployment_note_create.adoc
docs/ecctl_deployment_note_create.md
docs/ecctl_deployment_note_list.adoc
docs/ecctl_deployment_note_list.md
docs/ecctl_deployment_note_show.adoc
docs/ecctl_deployment_note_show.md
docs/ecctl_deployment_note_update.adoc
docs/ecctl_deployment_note_update.md

When adding documentation regarding ECE specific commands
we forgot to mark the `ecctl deplyoment note` command and its
subcommands as one of them. This patch fixes this issue.
Closes https://github.com/elastic/ecctl/issues/437
Let's not confuse our users :)
By running `make docs`

docs: Set deployment node command as ECE only

---

go.mod
go.sum

Updates the elastic/cloud-sdk-go to the latest available version which
contains the plan tracker fix and a `go-multierror` bugfix version.
Also, it removes a replace directive for a dependency no longer used.
Have `ecctl` use the latest version of the plan tracker.

mod: Update sdk to fix plan tracker bugs

---

cmd/comment/create.go
docs/ecctl_comment.adoc
docs/ecctl_comment.md
docs/ecctl_comment_create.adoc
docs/ecctl_comment_create.md

Aligns the text and help messages of the `comment create` command with the other sub-commands ( list and show )

alings create comment command texts

---

.github/workflows/branch.yml

Adds a GitHub action which creates a new branch when a tag is pushed
with the tag's MAJOR.MINOR. If the branch already exists, the action
will fail, but it can be ignored. GitHub actions has no way to set the
step as successful on failure, we'd need to modify the source code of
the used action.

release: Add branch GitHub action

---

.github/workflows/branch.yml

Last fix to the branch action, it was using a shallow checkout, it needs to use 0 depth to be able to describe the tag.

release: Use fetch-depth:0 on checkout

---

.golangci.yml
build/Makefile.deps

Uses the built in `go install` that newer versions of Go have to install
the Go binary dependencies that this project relies on.

scripts: Use go install rather than gobin

---

.github/workflows/branch.yml
Makefile
build/Makefile.deps
build/Makefile.version

Adds the `versionbump` binary and github action workflows:
Updates `branch-out` to bump the patch version and commit it to the
relevant branch.
`bump-main-version` checks out the `master` branch and updates the minor
version. Since Major version updates are rare enough where they can be
done manually (still leveraging `make major`).

release: Automate version updates on all branches

---

docs/ecctl-getting-started.asciidoc
pkg/ecctl/init.go
pkg/ecctl/init_test.go

Adds a link in the `ecctl init` workflow when the Elasticsearch Service
option has been selected to the ESS API Key feature page.
Additionally, updates the configuration precedence documentation to use
a different set of flags rather than `--user` and `--pass`, since these
are only relevant for ECE users.
Closes #505 
Unit & manual tested.

init: Add an ESS API Key creation link

---

cmd/deployment/elasticsearch/keystore/update.go
docs/ecctl_deployment_elasticsearch_keystore_update.adoc
docs/ecctl_deployment_elasticsearch_keystore_update.md

Improves the documentation for the `deployment elasticsearch keystore`
command adding more information about how to format the file that is
passed to the command, where to find more info and a couple of examples.
Closes #507

docs: Improve `elasticsearch keystore` cmd help

---

build/Makefile.deps

Removes the installation of Goreleaser from the main `deps` target since
it's not necessary to perform any of the development tasks and it can be
installed manually if a release needs to be manually run.
Broken Go builds.

scripts: Remove goreleaser from deps target

---

.github/workflows/on_master_generation.yml

This is a follow-up fix for https://github.com/elastic/ecctl/pull/524. In the added CI job name of the env variable with the Github token was set incorrectly.

Fix env variable name with Github token

---

pkg/ecctl/read_secret.go

Have to cast `syscall.Stdin` to `int` on Windows because Stdin is not simple 0 but `Handle` (`uintptr`) there according to the following Godoc. https://pkg.go.dev/syscall?GOOS=windows#pkg-variables
Add simple cast to `int`, which doesn't have any effect on operating systems where `syscall.Stdin` is 0 but do have on Windows where type of `syscall.Stdin` is not `int`.
The change in this PR will fix https://github.com/elastic/ecctl/issues/528.
I move to Windows but I want to keep using ecctl command. With this change, I have succeeded to not only install ecctl but also complete `ecctl init` as well as run e.g. `ecctl deployment list` without any problems.
Install and run it with `go1.17.2 windows/amd64` on my Windows 10.0.19043.

Windows: Absorb the difference of syscall.Stdin

---

README.md

Mentions the EC Terraform provider as the preferred tool to manage
deployments.
None
Some users are still relying on `ecctl` to create and manage ESS deployments, while the tool allows it since it can create deployments from a JSON definition, it's not the most suitable tool for the job.

docs: Add note about the EC Terraform provider

---

.goreleaser.yml

It's an attempt to fix https://github.com/elastic/ecctl/runs/4475470597?check_suite_focus=true. It looks like the issue is with config validation. 
Before this change I had locally:
```
$ goreleaser check -f .goreleaser.yml 
• loading config file       file=.goreleaser.yml
⨯ command failed            error=yaml: unmarshal errors:
line 28: field lang not found in type config.Build
```
With fix it seems to be valid now:
```
$ goreleaser check -f .goreleaser.yml
• loading config file       file=.goreleaser.yml
• checking config: 
• snapshotting     
• scm releases     
• project name     
• loading go mod information
• building binaries
• universal binaries
• creating source archive
• archives         
• linux packages   
• snapcraft packages
• calculating checksums
• signing artifacts
• …
```

Attempt to fix ecctl release

---

.goreleaser.yml

This is backport of https://github.com/elastic/ecctl/pull/537

Backport #537 to release branch

---

cmd/deployment/resource/delete.go
cmd/deployment/resource/restore.go
cmd/deployment/resource/shutdown.go
cmd/deployment/resource/start-maintenance.go
cmd/deployment/resource/stop.go
cmd/deployment/shutdown.go
cmd/deployment/update.go
cmd/platform/allocator/vacate.go

This PR fixes #560
Here are the reasons behind the correction.
- 2nd arg must be `os.Stdin` instead of `os.Stderr`. Otherwise, the confirmation gets stuck on reading.
- 3rd arg should be `ecctl.Get().Config.OutputDevice` to respect the config.
https://github.com/elastic/ecctl/issues/560
I don't want to use `--force` option to work #560 around on every delete; the `--force` option should be never ever used by human beings.
Run a couple of commands on my laptop.

Correct arguments on ConfirmAction()

---

.github/workflows/branch.yml
.github/workflows/release.yml

Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
echo ::set-output name=BRANCH::$(echo ${BRANCH} | cut -d '.' -f1-2 | tr -d 'v')
```
**TO-BE**
```yaml
echo "BRANCH=$(echo ${BRANCH} | cut -d '.' -f1-2 | tr -d 'v')" >> $GITHUB_OUTPUT
```
Closes #616 
None

Replace deprecated command with environment file

---

.github/workflows/branch.yml

The builtin GITHUB_TOKEN does not have permissions to bypass branch-protections.

Revert change to branch workflow GITHUB_TOKEN.

---

.github/workflows/branch.yml
.github/workflows/go.yml
.github/workflows/release.yml
.gitignore
.golangci.yml
.goreleaser.yml
build/Makefile.build
build/Makefile.deps
build/Makefile.dev
build/errcheck-exclusions.txt
go.mod
go.sum

The release github action is currently broken:
We were using the `latest` gorelease-action, which had changed from 1->2 recently. The main breaking change for us was that `--rm-dist` flag was replaced by `--clean`
But this change causes some other changes:
- Some smaller changes in the goreleaser config
- To run the newest goreleaser, we have to upgrade to golang 1.23.0
- When using go 1.23.0, golangci-lint also needs upgrading
- golanci-lint on the new version also has some config deprecations/changes 
But with all these changes, the local build/lint runs without errors or warnings and the dry-run gorelease also runs through (hopefully the same is the case in the github action).

Fix goreleaser-action

---

cmd/platform/instance-configuration/show.go
docs/ecctl_platform_instance-configuration_show.adoc
docs/ecctl_platform_instance-configuration_show.md

Backports the changes in https://github.com/elastic/ecctl/pull/669 to branch `1.14`, in order to prepare for a patch release.

Backport #669 to 1.14 branch

---

.github/workflows/branch.yml
.github/workflows/go.yml
.github/workflows/release.yml
.gitignore
.golangci.yml
.goreleaser.yml
build/Makefile.build
build/Makefile.deps
build/Makefile.dev
build/errcheck-exclusions.txt
go.mod
go.sum

Backport https://github.com/elastic/ecctl/pull/667 to branch `1.14`.

Fix goreleaser version (#667)

---

cmd/deployment/elasticsearch/keystore/update.go
docs/ecctl_deployment_elasticsearch_keystore_update.adoc
docs/ecctl_deployment_elasticsearch_keystore_update.md

This will backport the following commits from `master` to `1.8`:

[1.8] [DOCS] Remove broken link to Cloud API doc (#679)

---

cmd/deployment/elasticsearch/keystore/update.go
docs/ecctl_deployment_elasticsearch_keystore_update.adoc
docs/ecctl_deployment_elasticsearch_keystore_update.md

This will backport the following commits from `master` to `1.6`:

[1.6] [DOCS] Remove broken link to Cloud API doc (#679)

---

cmd/deployment/elasticsearch/keystore/update.go
docs/ecctl_deployment_elasticsearch_keystore_update.adoc
docs/ecctl_deployment_elasticsearch_keystore_update.md

This will backport the following commits from `master` to `1.9`:

[1.9] [DOCS] Remove broken link to Cloud API doc (#679)

---

cmd/deployment/elasticsearch/keystore/update.go
docs/ecctl_deployment_elasticsearch_keystore_update.adoc
docs/ecctl_deployment_elasticsearch_keystore_update.md

This will backport the following commits from `master` to `1.10`:

[1.10] [DOCS] Remove broken link to Cloud API doc (#679)

---

cmd/deployment/elasticsearch/keystore/update.go
docs/ecctl_deployment_elasticsearch_keystore_update.adoc
docs/ecctl_deployment_elasticsearch_keystore_update.md

This will backport the following commits from `master` to `1.13`:

[1.13] [DOCS] Remove broken link to Cloud API doc (#679)

---

go.mod
go.sum

Backport #661 and #677 module updates to `1.14` branch.

Backport #661 and #677 module updates to 1.14

---

.github/workflows/release.yml

As discussed in [slack](https://elastic.slack.com/archives/C01KXR8BQ2F/p1737041355441439?thread_ts=1737028137.317849&cid=C01KXR8BQ2F), we should remove the "Update AWS cli" step from the release workflow, because `aws-cli` should be installed by default in GH actions.

Remove AWS CLI update from release workflow

---

.github/workflows/release.yml

Backport #696 to branch `1.14`.

[Backport] Remove AWS CLI update from release workflow (#696)

---

go.mod

As discussed in [slack](https://elastic.slack.com/archives/C01DJ3DC0AX/p1737122643411819?thread_ts=1736776556.219929&cid=C01DJ3DC0AX), versions v1.14.1 and v1.14.2 are broken. This PR retracts both of these versions.
//cc @jamietanna

Retract verstions v1.14.1 and v1.14.2

---

docs/reference/ecctl-example-create-deployment.md
docs/reference/ecctl-examples.md
docs/reference/ecctl_deployment_search.md
docs/reference/ecctl_platform_allocator_list.md
docs/reference/ecctl_platform_allocator_search.md
docs/reference/ecctl_platform_runner_search.md

Follow up to #707 
When using cross-repo links, the path should be relative to the `docset.yml` not the full path within the repo ([updated docs-builder docs](https://elastic.github.io/docs-builder/syntax/links/#cross-repository-links)).

[docs] Clean up cross-repo links

---

.gitignore
docs/docset.yml
docs/redirects.yml
docs/reference/ecctl-release-notes.md
docs/release-notes/index.md
docs/release-notes/toc.yml

Creates a new ECCTL release notes folder so release notes can match other release notes in our docs.
After this is done, I need the hosted apps team to help me to rewire any auto-generated content to append to these files rather than create the old `.adoc` files, and update the release template to link to these new urls instead, in the following format:
https://www.elastic.co/docs/release-notes/ecctl#ecctl-<version.minor>
e.g. https://www.elastic.co/docs/release-notes/ecctl#ecctl-1.15.0
Will sunset the [random empty page](https://www.elastic.co/docs/reference/ecctl/ecctl-release-notes) when we have proper redirect support.
Need to also ship https://github.com/elastic/docs-builder/pull/1511 to get this to done
Fixes https://github.com/elastic/docs-content-internal/issues/47
- The migration …

new release notes directory, resurrect recent notes

---

docs/docset.yml
docs/release-notes/breaking-changes.md
docs/release-notes/toc.yml

Redoing my fix from https://github.com/elastic/ecctl/pull/733: the fix wasn't valid for the location where the release notes need to be hosted

add a hidden file to make the child TOC valid

---

cmd/deployment/trafficfilter/association/command.go
cmd/deployment/trafficfilter/command.go
cmd/deployment/trafficfilter/create.go
cmd/deployment/trafficfilter/delete.go
cmd/deployment/trafficfilter/list.go
cmd/deployment/trafficfilter/show.go
docs/reference/ecctl_deployment.md
docs/reference/ecctl_deployment_traffic-filter.md
docs/reference/ecctl_deployment_traffic-filter_association.md
docs/reference/ecctl_deployment_traffic-filter_association_create.md
docs/reference/ecctl_deployment_traffic-filter_association_delete.md
docs/reference/ecctl_deployment_traffic-filter_create.md
docs/reference/ecctl_deployment_traffic-filter_delete.md
docs/reference/ecctl_deployment_traffic-filter_list.md
docs/reference/ecctl_deployment_traffic-filter_show.md
docs/reference/ecctl_deployment_traffic-filter_update.md

In ECH, traffic filter rulesets are being rebranded to network security policies. this PR updates the docs and the in-product strings
https://github.com/elastic/platform-docs-team/issues/682
prereq: https://github.com/elastic/docs-content/pull/1785/ + https://github.com/elastic/docs-content/pull/2047
see description
docs preview: https://docs-v3-preview.elastic.dev/elastic/ecctl/pull/735/reference/ecctl_deployment_traffic-filter

[doc] rebranding traffic filters to network security policies in ECH
