.github/workflows/go.yml

Changes the go build action to run the build on PRs and Push events

ci: run go build action in PRs

---

README.md
docs/ecctl-getting-started.asciidoc

Improve user documentation

---

docs/ecctl-getting-started.asciidoc
docs/page_header.html

This PR includes several documentation tweaks for the beta:
- Add a standard page header, as used by other books. (To remove this header in the future, simply delete `page_header.html`.)
- Replace the beta note on the overview page with the standard Elastic `beta[]` notice. 
- Simplify some of the revised wording on the overview page
Here's some output details:
Relates to https://github.com/elastic/ecctl/pull/22
These are consistency changes meant to follow the standard for Elastic books. 
Test built locally with `docbldecctl` and proofed the output.

Beta doc updates

---

cmd/deployment/list.go
docs/ecctl_deployment.md
docs/ecctl_deployment_list.md
pkg/deployment/list.go
pkg/deployment/list_test.go
pkg/formatter/templates/bindata.go
pkg/formatter/templates/text/deployment/list.gotmpl
pkg/formatter/text.go
pkg/formatter/text_template_utils.go
pkg/formatter/text_template_utils_test.go

Adds the deployment list command and an associated text template.
Cannot list deployments
Output:
```console
$ dev-cli deployment list
ID                                 NAME                          ELASTICSEARCH                      KIBANA                             APM                                APPSEARCH
709551ecd21143adbb7a37bbf36c4321   admin-console-elasticsearch   709551ecd21143adbb7a37bbf36c4321   -                                  -                                  -
83c2027d92c44aeba34378f44cf08137   logging-and-metrics           83c2027d92c44aeba34378f44cf08137   d140b6e35b0445a9afd4420f6c1b3b21   22043a1926a04aa6a91deadfec741636   -
89a54cee4a2847c291f520ac00760886   security-cluster              89a54cee4a2847c291f520ac00760886   -                                  - …
```

deployment: Add list command

---

cmd/deployment/search.go
docs/ecctl_deployment_search.md
pkg/deployment/search.go
pkg/deployment/search_test.go
pkg/formatter/templates/bindata.go
pkg/formatter/templates/text/deployment/search.gotmpl

Adds deployment search command with a text output template and examples
in the docs.
```console
$ dev-cli deployment search -f query_string_query.json
ID                                 NAME                          ELASTICSEARCH                      KIBANA   APM   APPSEARCH
e2874dbaa0db4ea2a44f39f00fcaad09   admin-console-elasticsearch   e2874dbaa0db4ea2a44f39f00fcaad09   -        -     -
```

deployment: Add search command

---

docs/ecctl-getting-started.asciidoc

docs: Remove tap pin step from brew instructions

---

Makefile

Change the version from `v1.0.0-rc1` to `v1.0.0-beta1`.
We're extending the Beta run for a while pending more user feedback.

Version: Change to v1.0.0-beta1

---

cmd/deployment/plan/cancel.go
cmd/deployment/resource/start-maintenance.go
cmd/deployment/resource/start.go
cmd/deployment/resource/stop-maintenance.go
cmd/deployment/resource/stop.go
go.mod
pkg/deployment/depresource/cancel_plan.go
pkg/deployment/depresource/cancel_plan_test.go
pkg/deployment/depresource/start.go
pkg/deployment/depresource/start_maintenance.go
pkg/deployment/depresource/start_maintenance_test.go
pkg/deployment/depresource/start_test.go
pkg/deployment/depresource/stop.go
pkg/deployment/depresource/stop_maintenance.go
pkg/deployment/depresource/stop_maintenance_test.go
pkg/deployment/depresource/stop_test.go

Changes code in `pkg/deployment/depresource` to use new common struct found in [pkg/deployment/params.go](https://github.com/elastic/ecctl/blob/master/pkg/deployment/params.go)
Closes: https://github.com/elastic/ecctl/issues/95
Code should reflect the recent changes regarding a common struct for all deployment resource commands.
Manually in a local ece environment and with unit tests

cmd: update resource params to use common struct

---

go.sum

Updates the hashes for go modules to the correct versions.

go.sum: Update hashes to the latest version

---

go.mod
go.sum

Updates the `cloud-sdk-go` dependency to it's latest release (v1.0.0-bc9) which introduces the following changes:
- Adds a Timeout field of time.Duration to the api.Config structure, allowing users to set the Timeout value for all API calls.
- Updates various dependencies to their latest versions.
Unit tests

dep: update cloud-sdk-go to v1.0.0-bc9

---

cmd/root.go
pkg/ecctl/app.go
pkg/ecctl/config.go

Adds the missing Timeout value
Timeout config was missing.

Add timeout values to ecctl.Config

---

.goreleaser.yml
docs/ecctl-getting-started.asciidoc

Added more specific instructions how to enable auto completion in the note following the brew install commands.

Add auto completion intruction to docs

---

cmd/deployment/create.go
docs/ecctl_deployment_create.md

cmd: Fix deployment create typo

---

docs/ecctl-getting-started.asciidoc

This PR updates the usage example to one that uses currently supported command syntax. 
Related to a private Slack convo with @Kushmaro (for my own reference: [link](https://elastic.slack.com/archives/DR6G16YAY/p1578409591003100))
Test built the docs output locally, looks clean:

Update usage example for beta1

---

docs/ecctl-release-notes.asciidoc
docs/index.asciidoc

This PR adds release notes for 1.0.0-beta1 in a new "Release notes" section to our official ecctl documentation.
Content is based on https://docs.google.com/document/d/1nUq8cCiuMingMxYU-GvPojyuDi94jXieuh_oMonQzd0/edit# with some edits.
Closes #26 
Content builds cleanly. Output:

Add beta1 release notes

---

.goreleaser.yml

Adds a `go mod tidy` command to the goreleaser to avoid `git in a dirty state` error when releasing.
Errors when releasing are not fun
By running a release.

misc: adds a `go mod tidy` command to the goreleaser.yml

---

.github/workflows/release.yml

Fixes the following error on build:
fix teh build
by checking the action in my own fork

Fix goreleaser gh actions workflow

---

go.mod
go.sum

Fixes the broken deployment notes command
Fixes the broken `deployment note` subcommands.

go.mod: Update cloud-sdk-go to v1.0.0-bc12

---

build/Makefile.deps
scripts/uname_arch.sh

This PR updates the deps makefile target to use make's inbuilt cache capabilities.
The main features are:
- cached binary dependencies
- versioned binary dependencies
- faster makefile targets which rely on the deps target
The main issue that this PR solves is that quite a few makefile targets depend on the deps target. The deps target currently pulls the binaries down each time it's invoked which is a lengthly time sink.

makefile: update deps target to use cache

---

docs/ecctl-getting-started.asciidoc
pkg/ecctl/init.go

This PR updates documentation to be consistent with our `init` command. I also made a small grammar mistake in a previous PR. Fixing it here 😄 
n/a
no one like bad grammer
n/a

docs: update documentation and fix small grammar mistake

---

docs/ecctl-release-notes.asciidoc

This PR adds a stub for the release notes for ecctl 1.0.0-beta2. Please add content!

Add release notes stub for 1.0.0-beta2

---

docs/ecctl-release-notes.asciidoc

Revert "Add release notes stub for 1.0.0-beta2"

---

README.md

Comments out the information that will be used after ESS API is public.
ESS API is still not generally available.

docs: Ammend Readme.md to clarify ECE only for now

---

.github/workflows/go.yml
.github/workflows/release.yml

Fixes a bug where checkout fails making the build check also fails.
failing builds are no good.

github actions: Update checkout action to v2

---

docs/release_notes/v1.0.0-beta2.adoc

Amends a small formatting bug.

Fix small formatting mistake on Release Notes

---

scripts/goreleaser-post-actions.sh
scripts/update-brew-tap.sh

Fixes the scripting that's broken

Fix GitHub release action

---

docs/ecctl-getting-started.asciidoc

Adds brew upgrade instructions to the official docs.

docs: Add brew upgrade instructions

---

.github/CODEOWNERS

misc: change codeowners

---

README.md
docs/ecctl-getting-started.asciidoc

The README makes reference to steroids, which could be misconstrued as a negative connotation. It doesn't add a lot of value to the tool either, so I'm thinking we could probably do without.
I think it does more harm than good. Removing those words makes the README much more amicable.
No test required. Docs only.

remove negative connotation

---

docs/ecctl-getting-started.asciidoc

Updates the getting-started ascii doc to reflect the project's current status of API availability.
Closes: https://github.com/elastic/ecctl/issues/257
Docs should reflect the current status of the project.

docs: update getting-started ascii doc

---

.github/CODEOWNERS

Adds Nik and Arianna as docs codeowners.
Tech writters should know what's going on with our docs!

docs: Add Nik and Arianna as CODEOWNERS

---

docs/ecctl-getting-started.asciidoc

It looks like I added a reference to Ansible and Terraform at some point that doesn't
actually belong into the ecctl docs. This PR removes that reference.

Remove reference to Ansible and Terraform

---

docs/ecctl-getting-started.asciidoc

This PR cherry picks a718611d218645cd9b71c53b848202d259c1ae57 into the beta2 docs branch.

Remove reference to Ansible and Terraform - cherry pick

---

README.md
docs/ecctl-getting-started.asciidoc
scripts/changelog.tpl.adoc

Adds references to Elasticsearch Service in our documentation for the release of ESS public API
Related: https://github.com/elastic/ecctl/issues/161

docs: add references to Elasticsearch Service

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
.github/ISSUE_TEMPLATE/GENERIC_QUESTION.md
.github/ISSUE_TEMPLATE/RELEASE_CHECKLIST.md

Updates issue templates with new team labels

misc: update issue template labels

---

cmd/deployment/create.go
cmd/deployment/create_help.go
docs/ecctl_deployment_create.adoc
docs/ecctl_deployment_create.md

In order to improve UX, this PR substitutes the word "idempotency token" for "request ID". The help text is also slightly changed to make it more understandable.

cmd: rephrase deployment create flag, error and  help text

---

cmd/deployment/update.go
go.mod
go.sum

Fix `failed converting *api.UserAgentTransport to *http.Transport` error
Fixes a printed error message which is just a warning.
Unit tested.

mod: Update vendor to 60b0cbb commit

---

cmd/platform/stack/command.go
go.mod
go.sum

Populates the new Region field on all of the stackapi calls.
Requires https://github.com/elastic/ecctl/pull/302 and https://github.com/elastic/cloud-sdk-go/pull/134 to be merged

stack: Populate stackapi Region field

---

cmd/platform/constructor/list.go
cmd/platform/constructor/maintenance.go
cmd/platform/constructor/show.go
go.mod
go.sum

Updates the constructor commands to use the region per API call.

constructor: Populate constructorapi Region field

---

cmd/platform/repository/create.go
cmd/platform/repository/delete.go
cmd/platform/repository/list.go
cmd/platform/repository/show.go
go.mod
go.sum

Populates the new Region field on all of the snaprepoapi calls.
Requires https://github.com/elastic/cloud-sdk-go/pull/136 to be merged

repository: Populate snaprepoapi Region field

---

cmd/platform/runner/list.go
cmd/platform/runner/resync.go
cmd/platform/runner/search.go
cmd/platform/runner/show.go
go.mod
go.sum

Populates the new Region field on all of the runnerapi calls.
Requires https://github.com/elastic/cloud-sdk-go/pull/138 to be merged

runner: Populate Region field API calls

---

developer_docs/NEW_COMMAND.md
developer_docs/STYLEGUIDE.md

Updates the developer docs with current information about the state
of the project.
Some of the information removed from the STYLEGUIDE.md will be moved
to cloud-sdk-go where it is relevant.
Related: https://github.com/elastic/ecctl/issues/335
no one likes broken links or information that isn't relevant anymore

docs: Update to reflect the current state of the project

---

go.mod
go.sum

Updates the `elastic/cloud-sdk-go` module to the latest version.
#335

release: Update cloud-sdk-go@v1.0.0 module

---

docs/ecctl-getting-started.asciidoc

Removes the beta disclaimer on the official docs.

docs: remove asciidoc beta disclaimer

---

Makefile

Bumps the master branch version to the upcoming feature version

version: Bump master branch to v1.1.0

---

scripts/update-brew-tap.sh

Configures the git username and email through `git config` command since
the environment variables seem to have no effect on the release target.
Broken release GitHub action.

release: Fix git commit by adding user and email

---

go.mod
go.sum
renovate.json

Updates the `go.mod` file to the latest patch versions and enables
renovate on the repo.

deps: Enable renovate and update

---

cmd/platform/allocator/list.go
docs/ecctl_platform_allocator_list.adoc
docs/ecctl_platform_allocator_list.md
go.mod
go.sum

Adds a new `--size` flag to the `platform allocator list` command.
Being able to list more than the default `100` allocators.

allocator: Add --size flag to list command

---

cmd/root.go
cmd/root_test.go

Fixes the problem where the `EC_API_KEY` environment variable wasn't
read.
The problem was that `viper` (correctly) unpacked the `EC_API_KEY` as
`api-key`, and since the `mapstructure` tags (in ecctl.Config) reference
`api_key`, the key is correctly un-marshaled when a config file is read,
but not when set via environment variables.
The fix is to set an alias `api_key` to the existing `api-key` key,
which is done in `cmd/root.go:143`.
v.RegisterAlias("api_key", "api-key")
The rest of the patch is necessary to provide at least some unit tests
to be able to assert this behavior.
Resolves #376

fix: ignored EC_API_KEY environment variable (#379) (Backport)

---

docs/ecctl-getting-started.asciidoc

Old: ec-getting-started-templates.html
New: ec-getting-started-solutions.html AND ec-getting-started-profiles.html
Updated wording as well. Needs to be backported to version 1.0.0-beta3.
Closes #383

Correct bad cross-product links

---

docs/ecctl-getting-started.asciidoc

Was missing part of the url for the link.

Fix typo in URL

---

docs/ecctl-getting-started.asciidoc

Update URLs 1.0.0b3

---

docs/ecctl-getting-started.asciidoc

Correct URL

---

docs/ecctl-getting-started.asciidoc

Another typo

---

scripts/changelog.tpl.md
scripts/update-brew-tap.sh

Ports the release fix back to the `1.0` branch. Ports the changes
from #367 and #366 
#382

release: Fix 1.0 branch release job

---

go.mod
go.sum
pkg/ecctl/app_test.go

Updates the cloud-sdk-go dependency to the latest release (v1.2.0)
Related: https://github.com/elastic/ecctl/issues/436

deps: Update to cloud-sdk-go v1.2.0

---

.github/ISSUE_TEMPLATE/RELEASE_CHECKLIST.md
developer_docs/RELEASE.md

This PR adds information about releases to our docs.

docs: Improved release documentation

---

docs/release_notes/v1.2.0.adoc

Replaces #441 but with signed commits so GH will let us merge

fixup: release notes

---

cmd/deployment/note/command.go
docs/ecctl_deployment.adoc
docs/ecctl_deployment.md
docs/ecctl_deployment_note.adoc
docs/ecctl_deployment_note.md
docs/ecctl_deployment_note_create.adoc
docs/ecctl_deployment_note_create.md
docs/ecctl_deployment_note_list.adoc
docs/ecctl_deployment_note_list.md
docs/ecctl_deployment_note_show.adoc
docs/ecctl_deployment_note_show.md
docs/ecctl_deployment_note_update.adoc
docs/ecctl_deployment_note_update.md

This is a backport of https://github.com/elastic/ecctl/pull/446

backport: Set deployment node command docs as ECE only

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md

Updates bug issue template to request more information about usage.
Make debugging easier :)

gh issues: Update bug issue template

---

cmd/deployment/trafficfilter/delete_test.go

Small fix to traffic filter `deleteCmd` test.

traffic-filter: Fix deleteCmd test

---

go.mod
go.sum

The result of 
```
go get github.com/elastic/cloud-sdk-go@v1.3.0
go mod tidy
```
to update to the latest cloud-sdk-go

Bump to cloud-sdk-go v1.3.0

---

.github/workflows/go.yml
.github/workflows/release.yml

Updates the Go version to 1.16

Update Go to 1.16

---

.github/workflows/branch.yml
.github/workflows/release.yml

Fixes the two GitHub Actions for the release.

Fix release and branch actions

---

Makefile

Bumps the master branch version to `v1.4.0`.

version: Bump to v1.4.0

---

.github/workflows/release.yml
scripts/update-brew-tap.sh

Patches the brew formula script and updates the goreleaser version to
the latest available version.
Fix the release job once and for all.

release: latest round of goreleaser patches

---

.github/workflows/go.yml
.github/workflows/release.yml

Updates the Go version to the latest available version.

go: Update to latest `1.17` version

---

build/Makefile.build
developer_docs/RELEASE.md

Updates the `RELEASE.md` doc with the latest information on how to ship
a new version of `ecctl`.

release: Update releasing doc

---

docs/ecctl-getting-started.asciidoc

I just set up ecctl for the first time using this guide, and some of the example output was out of date.

[docs] Update docs for getting started

---

go.mod
go.sum

Updates `cloud-sdk-go` to `v1.6.0`

Update cloud-sdk-go version

---

.github/workflows/branch.yml

This PR fixes release job in Github Actions

Fix release job

---

build/Makefile.deps

Fix make target like in https://github.com/elastic/cloud-sdk-go/pull/357

Fix make target

---

.github/workflows/branch.yml

Remove Github token

---

.github/workflows/go.yml
.github/workflows/on_master_generation.yml
NOTICE

This PR adds auto-generation of `NOTICE` file on every commit to `master`. Right now we are missing any automation around that.
Unfortunately, we can test this PR only when it will be merged.
Similar to https://github.com/elastic/terraform-provider-ec/pull/372

Auto-generate NOTICE

---

cmd/auth/key/create.go
docs/ecctl_auth_key_create.adoc
docs/ecctl_auth_key_create.md
go.sum

Rel: https://github.com/elastic/cloud/issues/93007

Remove deprecated reauthenticate API call from auth key creation command

---

cmd/auth/key/create.go
go.mod
go.sum

Fixes a panic in the `userauthapi.CreateKey()` call due to the missing
`api.API`.
https://github.com/elastic/cloud-sdk-go/pull/378
Fixes the following panic:
```console
$ ecctl auth key create --description some_description
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x100c013b4]
goroutine 1 [running]:
github.com/elastic/cloud-sdk-go/pkg/api/userapi/authapi.CreateKey({0x0, {0x16f8bf623, 0x1}})
/Users/marclop/go/pkg/mod/github.com/elastic/cloud-sdk-go@v1.7.1-0.20220114092459-af5391db2912/pkg/api/userapi/authapi/createkey.go:60 +0x124
github.com/elastic/ecctl/cmd/auth/key.glob..func2(0x10164b3a0, {0x1400039a560, 0x0, 0x2})
/Users/marclop/repos/elastic/ecctl/cmd/auth/key/create.go:32 +0x5c …
```

apikey: Fix broken `user apikey create` command

---

.github/workflows/branch.yml
.github/workflows/on_master_generation.yml
.github/workflows/release.yml

Some of the build/release actions were failing because the installed go version is 1.17 instead of 1.19.

Update go to 1.19 for github actions

---

catalog-info.yml

This change introduces the necessary yaml file in order for Backstage to pick-up this service in its database.
Someone may need to review the metadata. I did the best I could to check to make sure the info was accurate. But just having a second set of eyes would help.
N/A

Adding ecctl to backstage

---

.github/ISSUE_TEMPLATE/RELEASE_CHECKLIST.md
developer_docs/RELEASE.md

ecctl release docs: Add example PR for docs change.

---

.github/workflows/branch.yml
.github/workflows/go.yml
.github/workflows/on_master_generation.yml
.github/workflows/release.yml
NOTICE
build/Makefile.deps
build/Makefile.dev
go.mod
go.sum
pkg/util/random.go

Update of `cloud-sdk-go`. 
Unfortunately the linter command didn't work anymore so I also had to updated some dependencies:
- golangci-lint 1.50.1 doesn't work when go 1.20 is installed -> updated to latest version
- updated go everywhere to 1.20
- removed golint, as it is deprecated and unmaintainted. According to the golint site, `go vet` is a replacement
- with 1.20, `rand.Seed` is deprecated and the random number generator is seeded randomly by default

Update cloud-sdk-go to 1.14.0

---

.github/workflows/branch.yml
.goreleaser.yml
build/Makefile.build
build/Makefile.deps

Updates to latest goreleaser, fixes all configs/parameters that are deprecated with this release.
The 'replacements' parameter was removed in goreleaser. The name now has to be built directly in the file-name template.
(See: https://github.com/goreleaser/goreleaser/issues/3588#issuecomment-1326457874)

Fix goreleaser config.

---

NOTICE
cmd/util/track_test.go
go.mod
go.sum

Update cloud-sdk-go to v1.15.0.

Update cloud-sdk-go to v1.15.0

---

.github/workflows/branch.yml
developer_docs/RELEASE.md

Revert "Update ecctl release process for patch versions"

---

.github/CODEOWNERS
catalog-info.yml

Rename stateful applications -> hosted applications as part of team rename. The github team has already been renamed, so this points code owner etc at new team name.

Rename stateful applications -> hosted applications

---

.github/workflows/docs-build.yml

Add ability to trigger docs-build manually
Needed to updated the link index.

Add ability to trigger docs-build manually

---

Makefile
go.mod
go.sum
notes/v1.14.4.md

Pulls in cloud-sdk-go `[v1.24.1](https://github.com/elastic/cloud-sdk-go/tree/refs/tags/v1.24.1)`. Which includes: [PR](https://github.com/elastic/cloud-sdk-go/pull/498) to support the Integration Server payload when building update payload from get response. (eg `ecctl deployment show 7d8ef46efeae4490a48eba6b91b704d6 --generate-update-payload`)
Rel: https://github.com/elastic/ecctl/issues/722
When a user gets a deployment with the update payload flags (eg `ecctl deployment show 7d8ef46efeae4490a48eba6b91b704d6 --generate-update-payload`) the integration server payload is always excluded even if the cluster has an integrations server running.
Example output:
```
json.resources.integrations_server = null;
```
```
➜  bin git:(master) ✗ EC_CONFIG=qa ./ecctl deployment show …
```

Prepare 1.14.4 Patch Release

---

docs/docset.yml
docs/release-notes/toc.yml

related to https://github.com/elastic/docs-builder/issues/764

Fix TOC so docs build can include ECCTL release notes

---

notes/v1.14.0.md
notes/v1.14.1.md
notes/v1.14.2.md
notes/v1.14.3.md
notes/v1.15.0.md

Link to new release doc where applicable (eg https://www.elastic.co/docs/release-notes/ecctl#ecctl-1.14.1). Older links still point at legacy docs (eg https://www.elastic.co/guide/en/ecctl/1.13/ecctl-release-notes-v1.13.0.html)

Update release notes links

---

.github/ISSUE_TEMPLATE/RELEASE_CHECKLIST.md
developer_docs/RELEASE.md
scripts/changelog.tpl.md
scripts/generate-changelog.sh

* Updates changelog tooling (`make changelog`) to stop generating deprecated asciidocs
* Updates release issue template to reflect current steps
* Updates release docs to reflect process following migration away from asciidocs 
This reflects the process used to release v1.15.0 
Along with manual testing of `make changelog`

Update release process following docs migration

---

cmd/deployment/show.go
docs/reference/ecctl_deployment_show.md

Clarifies show docs per discussion in this [issue](https://github.com/elastic/ecctl/issues/723#issuecomment-3026070459).

Clarify show deployment docs
